[package]
name = "safe_iot"
version = "0.1.0"
authors = ["hunterlester <guilfordhunter@gmail.com>"]

[dependencies]
safe_core = { path = "safe_client_libs/safe_core", version = "~0.23.0"}

[features]
use-mock-routing = ["safe_core/use-mock-routing"]
